### ISSUE TITLE
Error on link when setting custom days/views expiration

### ISSUE THREAD

**Issue by tony-engineering** [uhinze/pwdrop#7]
Hello Ulrich, I tried to use your password protector and ran into the described issue.

Environment: Firefox 78.7.0esr (64-bit) on Debian 10

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ajoii4yekw03kmvse4ms.gif)

**Comment by uhinze** [comment]
Thanks for spotting this! Fixed in c5d32cf4a0636f5840c628c0ae165672b661fc80
