### ISSUE TITLE
Link is not generated when disabling days/views expiration

### ISSUE THREAD

**Issue by tony-engineering** [uhinze/pwdrop#8]
Hello, I tried to disable days/views expirations and ran into the described issue.

Environment: Firefox 78.7.0esr (64-bit) on Debian 10

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/3zpd3qbh3hlwqu9keyri.gif)

**Comment by uhinze** [comment]
Thanks for spotting. Fixed in 05cab716bf6db7df3c03c7ba013af53391867142
